### ISSUE TITLE
Send to backpack button is big on firefox

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges-badges#11]
"All my friends have big butt[on]s" - Pee Wee Herman

![screenshot from 2013-10-04 16 07 50](https://f.cloud.github.com/assets/64711/1272882/2ce3acd4-2d39-11e3-95df-df0a79d47786.png)

**Comment by ghost** [comment]
That's actually the size specified in the design: http://cl.ly/image/1U3N0N3z3U0z

The text wrapping is obviously a problem.  I'll fix that.  Should I shrink the button as well?

**Comment by ghost** [comment]
Addressed by #12.  I shrunk the button slightly, reduced the font size slightly, and prevented text wrapping.  It's still a pretty big button, though, as specified in the design.

**Comment by ghost** [comment]
Just a big ol' button.
