### ISSUE TITLE
The following dependencies do not install on npm install

### ISSUE THREAD

**Issue by mgballard** [mozilla/openbadges-badges#13]
Should be added to package > dependencies
- [ ] cookie-jar
- [ ] qs
- [ ] oauth-sign
- [ ] aws-sign
- [ ] hawk
- [ ] aws-sign
- [ ] http-signature
- [ ] node-uuid
- [ ] mime
- [ ] tunnel-agent
- [ ] json-stringify-safe
- [ ] forever-agent
- [ ] form-data

**Comment by andrewhayward** [comment]
Hmm... none of those are (direct) dependencies though.

**Comment by mgballard** [comment]
Shouldn't dependencies of dependencies install automatically on npm install?

**Comment by andrewhayward** [comment]
Perhaps obvious questions, but worth asking:
- Did `npm install` throw up any errors at all?
- Have you tried blowing away your `node_modules` folder, and `npm install`ing again?

**Comment by cmcavoy** [comment]
I think this is unique to your setup @mgballard let's troubleshoot. Closing this for now.
