### ISSUE TITLE
Find alternative to Mandrill for OBB emails

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges-badges#14]
Alternatively, find a way to not include Mandrill links in the emails. We don't want Mandrill tracking the emails.

**Comment by andrewhayward** [comment]
I'm pretty sure there's a setting somewhere in Mandrill to turn this off. It's supposed to be a 'feature'.

**Comment by ghost** [comment]
Yep, there totally is.  I went ahead and removed click tracking and open tracking from our account.  Good call!

**Comment by cmcavoy** [comment]
As long as we remove click tracking, Mandrill is fine for now.
