### ISSUE TITLE
Design theme / brand for site

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges-badges#17]

**Comment by iamjessklein** [comment]
![obb-page1](https://f.cloud.github.com/assets/535012/1346933/8e210a32-36a8-11e3-939c-cff64d97d55d.png)
![obb-page2](https://f.cloud.github.com/assets/535012/1346934/8f8a0950-36a8-11e3-9fa0-4b88af4d48c1.png)
![obb-page3](https://f.cloud.github.com/assets/535012/1346935/9140aad8-36a8-11e3-8a26-a05a6dac309f.png)

**Comment by threeqube** [comment]
Will we have media upload capability for badge applications?

**Comment by iamjessklein** [comment]
I was unclear of the requirements on this - @carlacasilli?

**Comment by carlacasilli** [comment]
This depends on if we're using aestimia, as I thought we were. We should if we go that route. If claim codes, then we'll own them. @iamjessklein we should talk more about this

**Comment by iamjessklein** [comment]
Right, so @christensenep - we should probably be using that media uploader that we used for the CSOL site.

**Comment by cmcavoy** [comment]
I don't think we have enough time to add media upload for MozFest. We only
allowed text evidence for CEM, which saved us a lot of time. I'm up for
discussing with @christensenep & all in the stand tomorrow, but think this
is a stretch goal instead of a requirement for MozFest. Post-Mozfest it's
for sure possible.

On Thu, Oct 17, 2013 at 4:54 PM, iamjessklein notifications@github.comwrote:

> Right, so @christensenep https://github.com/christensenep - we should
> probably be using that media uploader that we used for the CSOL site.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadges-badges/issues/17#issuecomment-26556421
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
What is this PR? https://github.com/mozilla/openbadges-badges/pull/21#issuecomment-26562524

**Comment by carlacasilli** [comment]
Hey, @cmcavoy didn't we agree that we would use aestimia for these badges? Does text evidence include links? If so, that may work, otherwise, if there's no possibility of letting people upload evidence then it'll be necessary to make these all claim code badges. That's a bummer if we're launching the OBb at MozFest.

**Comment by cmcavoy** [comment]
Offline discussion summary: We're going to use Aestimia, aestimia can
handle text evidence out of the box. The links will be in the text. You'll
have to cut and paste the links, they won't automatically appear as 'links.'

On Thu, Oct 17, 2013 at 9:03 PM, Carla Casilli notifications@github.comwrote:

> Hey, @cmcavoy https://github.com/cmcavoy didn't we agree that we would
> use aestimia for these badges? Does text evidence include links? If so,
> that may work, otherwise, if there's no possibility of letting people
> upload evidence then it'll be necessary to make these all claim code
> badges. That's a bummer if we're launching the OBb at MozFest.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadges-badges/issues/17#issuecomment-26567550
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by carlacasilli** [comment]
:+1:

**Comment by iamjessklein** [comment]
Some feedback notes for @christensenep on implementation:
- every so often the badge descriptions are too long, we should limit the #of characters or just display the "short" description on the thumbs, as we did for CSOL.
- The recommendations aren't displaying on the "More Open Badges Badges" section
- Alerts should be in red text with white padding and notifications should be in blue text with white padding
- tabzilla should drop down (it currently links)

-on badge acceptance flow page: align "enter your email add...." with the input box.

Looking really crisp, Erik!

**Comment by iamjessklein** [comment]
Reassigning to @christensenep for the implementation notes

**Comment by ghost** [comment]
Regarding the badge description length:  If we want to do the short/long descriptions like we did for CEM, let me know and I will add in support for this.  Otherwise, we'll need to make some of the longer descriptions shorter.

Regarding the recommendations:  ~~These are keyed off of badge categories, and currently none of the badges have any categories, so it can't find other badges to recommend.  We'll need to add categories to badges to make the recommendations work (or failing that, I can change it to not use the recommendation system and just show four random badges).~~ Upon further investigation, the recommendation code is really CSOL-specific, so I'm just going to show four random badges.

The tabzilla issue is fixed in #27

**Comment by iamjessklein** [comment]
Nice, with regards to how to style the notifications, this is what I am thinking of: 

![notification](https://f.cloud.github.com/assets/535012/1385634/837acb1e-3b61-11e3-8598-6a5489358c4b.png)

**Comment by threeqube** [comment]
Talking to @carlacasilli about description. As per conversation with @christensenep I owe him answers to the following:
- short and long descriptions of each open badges badge (or condense current descriptions as they are too long) - need @carlacasilli for this (or at least direction so I can help)
- a decision on whether we'll make open badges badges a different issuer or a different program
- if a different program, decision on name of program, i.e. open badges as issuer and open badges as program too?
- update the open badges badges to new issuer or program depending on what we decide

Stay tuned.

**Comment by carlacasilli** [comment]
Have written a short description for the MOBb and @jadeforester will be inputting this per @threeqube directions.

https://docs.google.com/spreadsheet/ccc?key=0AnUOR-0CBMsTdDFGa05tUlQzMDZzLVFZWmJfZHR1UXc#gid=4

**Comment by cmcavoy** [comment]
Just to be clear, @christensenep is going to:
- [ ] show short descriptions when you click on the badge.

**Comment by threeqube** [comment]
Just to round out:

We agreed on the following:
- short and long descriptions of each open badges badge - These will be input into badger.openbadges.org using the same convention as we did for CEM, separated by an "*". All short and long open badges badges descriptions should be input by the time it's Erik's morning. 
- a decision on whether we'll make open badges badges a different issuer or a different program - Open badges badges will be a different program called "Open Badges Badges" within badger.openbadges.org
- if a different program, decision on name of program, i.e. open badges as issuer and open badges as program too? - same as above
- update the open badges badges to new issuer or program depending on what we decide - This will be done by the time it's Erik's morning.

**Comment by jadeforester** [comment]
All input with Carla's revisions, short/long descriptions and under new program "Open Badges Badges."

-Jade

Jade Forester
Global Coordinator + Liaison
Mozilla Foundation
http://openbadges.org
@openbadges | @jade_forester

**Comment by carlacasilli** [comment]
@iamjessklein + @mgballard does this branding extend to the criteria pages, yet? I just claimed a mozfest badge and saw the CEM branding.

![screen shot 2013-10-24 at 3 50 29 am](https://f.cloud.github.com/assets/1039302/1398463/c62f1bf4-3ca1-11e3-89ac-33c4091e35c4.png)

**Comment by threeqube** [comment]
@mgballard any update on this?

**Comment by threeqube** [comment]
This is done. A little weird home and logout menu items but good for now. 

![screen shot 2013-10-27 at 9 52 04 am](https://f.cloud.github.com/assets/1424627/1415255/5cdc11c6-3eee-11e3-9e89-98ac29ee6cb6.png)
