### ISSUE TITLE
Design badges for Open Badges

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/openbadges-badges#20]

**Comment by iamjessklein** [comment]
First draft:
![obb-draft1](https://f.cloud.github.com/assets/535012/1317992/ff8ab168-32b2-11e3-8add-e7147c2655ed.png)

**Comment by iamjessklein** [comment]
badges missing from mockup: Open Badgemaker and Open Bagineer

subtract Model Funder.

I am not loving the orange and yellow color combination and @carlacasilli does not like the diaper.

**Comment by iamjessklein** [comment]
Here is the latest iteration:
![obb3](https://f.cloud.github.com/assets/535012/1346011/e92d76d6-3699-11e3-8adc-df9e947c2b69.png)

**Comment by threeqube** [comment]
Ha, I love the evolution of the badgling. :)

**Comment by carlacasilli** [comment]
Glad that the mortarboard now has a tassel. :hamster: Wondering if the pale yellow bkgrds have gotten too light on this latest iteration?

Also wondering if Mayor McBadge's tophat can look a bit more quirky? @iamjessklein And maybe the two lines on the bottom of the page flow for ecosystem architect are a little busy and can be removed? 

And thinking that Badge Orator (that keeps showing up as Butterfly) should possible be a mouth…

**Comment by iamjessklein** [comment]
thanks @carlacasilli - might also rethink "badgeling" and use a caterpillar graphic.

**Comment by iamjessklein** [comment]
Latest mockups:
![obb-fri](https://f.cloud.github.com/assets/535012/1361351/fcfd452a-3805-11e3-9fc0-f44d3e3d4d7a.png)

**Comment by carlacasilli** [comment]
Hey, just to loop back on this. Let's try a less radical color or reduce the intensity of the inner hexagon for the pink ones. Looking really good, @iamjessklein

**Comment by iamjessklein** [comment]
Here are the updates:

![badgademic](https://f.cloud.github.com/assets/535012/1382639/393c8950-3b31-11e3-99fe-04254704cfcd.png)
![bagineer](https://f.cloud.github.com/assets/535012/1382640/39430ece-3b31-11e3-814e-d67683a84ca2.png)
![badgespotter](https://f.cloud.github.com/assets/535012/1382642/394686da-3b31-11e3-8af8-6fb9dc182a81.png)
![badgemaker](https://f.cloud.github.com/assets/535012/1382641/39468162-3b31-11e3-8101-347347e72176.png)
![badgeling](https://f.cloud.github.com/assets/535012/1382643/3947a286-3b31-11e3-8e83-3f3b4a10cf9f.png)
![badgehappy](https://f.cloud.github.com/assets/535012/1382644/3947c284-3b31-11e3-9b5c-e479ff27db0c.png)
![badgetechnician](https://f.cloud.github.com/assets/535012/1382645/3949ae8c-3b31-11e3-9033-884ba658e6d2.png)
![ecosystemarchitect](https://f.cloud.github.com/assets/535012/1382646/394bcb54-3b31-11e3-9674-51f6d4308ffe.png)
![mayormcbadge](https://f.cloud.github.com/assets/535012/1382647/394ef720-3b31-11e3-9f6b-bcd2dc80aed4.png)
![friendofopenbadges](https://f.cloud.github.com/assets/535012/1382648/394f731c-3b31-11e3-8efe-015b1540983f.png)
![orator](https://f.cloud.github.com/assets/535012/1382649/395154ac-3b31-11e3-9501-45b52e326509.png)
![thinkerer](https://f.cloud.github.com/assets/535012/1382650/3952f23a-3b31-11e3-99e7-2f15d146e04f.png)

**Comment by iamjessklein** [comment]
on IRC @carlacasilli approved. I am closing the issue.

**Comment by carlacasilli** [comment]
:+1:
