### ISSUE TITLE
Final copy to be provided

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/openbadges-badges#25]
The current copy on the site was made up by either @christensenep or myself and should be replaced with real copy. 

cc/ @threeqube @carlacasilli

**Comment by threeqube** [comment]
@carlacasilli let me know if you'd like me to help with this.

**Comment by emgollie** [comment]
@carlacasilli @threeqube I can help with this first thing Wed morning if we want to discuss over/after breakfast.

**Comment by emgollie** [comment]
Thoughts? Copy per http://obb-dev.herokuapp.com/badges:

DESCRIPTION
Welcome to the home for Open Badges badges. These badges are intended to recognize people who are leading and growing this ecosystem. Mozilla designed these badges to celebrate these individuals' commitment to openness and involvement in Open Badges. 

To learn about ways that you might participate and earn these badges, [action]. In cases where a prospective badge earner can demonstrate the criteria needed to earn the badge, they can be nominated by someone or even suggest themselves.

What you'll see here is an initial set of badges for these evangelists, thinkers and doers. Keep coming back to take part in this system as it grows!

BOX
Have a claim code? Enter it here. 

BUTTON
Claim

**Comment by carlacasilli** [comment]
A possible rewrite: 

Welcome to the home for Mozilla Open Badges badges. These initial set of badges celebrate the dynamic community members involved in leading, building, and growing the open badges ecosystem: the evangelists, thinkers and doers. They represent different forms of individual commitment to openness in areas such as assessment, peer-review, technology, and alternative credentialing. 

Many of these badges can be earned by providing appropriate evidence, so feel free to dive in and nominate yourself or others for them. And please return frequently to see the new badge-earning opportunities as they become available and participate in the system as it grows!

To learn more about open badges, please visit http://openbadges.org. ~~how you might participate and earn these badges, visit http://openbadges.badges.org (check with @threeqube on this link).~~ 

/cc Pls. review with comments @threeqube @emgollie

**Comment by emgollie** [comment]
The URL is http://badges.openbadges.org, but people will be on that page already when they read this. Updated:

Welcome to the home for Mozilla Open Badges badges. This initial set of badges celebrates the dynamic community members involved in leading, building, and growing the Open Badges ecosystem. They represent different forms of individual commitment to openness in areas such as assessment, peer review, technology, and alternative credentialing.

To learn how you might join these evangelists, thinkers, and doers in earning these badges, browse the badges below. Many of them can be earned by providing appropriate evidence. We invite you to dive in and nominate yourself or others for them. 

Come back to see new badge-earning opportunities as they become available and participate in the system as it grows!

**Comment by carlacasilli** [comment]
:+1:  :smile_cat:

**Comment by emgollie** [comment]
Hi friends, I think this copy looks too lengthy on the page: http://badges.openbadges.org/badges. Knowing that we might be too time-crunched to create a separate About page, should we consider a) trimming the intro copy to one short paragraph, or b) having the bulk of the copy live below the viewable badges? I think we want to get people to claim badges and view them sooner. Thoughts?

**Comment by threeqube** [comment]
Agreed, don't think this is working well aesthetically.

**Comment by emgollie** [comment]
Discussed with @cmcavoy @threeqube. Thanks for implementing these changes @cmcavoy.

HOMEPAGE HEADER COPY:

Mozilla Open Badges badges celebrate people who are leading & building this global community. Learn more [link to Welcome page: badges.openbadges.org/welcome].

NEW "WELCOME" PAGE COPY (left justify copy if possible):

Welcome to the home for Open Badges badges. This initial set of badges represent different forms of individual commitment to openness in areas such as assessment, peer review, technology, and alternative credentialing.

To learn how you might join these evangelists, thinkers, and doers in earning these badges, browse the badges here [link to homepage]. Many of them can be earned by providing appropriate evidence. We invite you to dive in and nominate yourself or others for them.

Come back to see new badge-earning opportunities as they become available and participate in the system as it grows!

**Comment by cmcavoy** [comment]
Filed this as a pull request (#31) but went ahead and pushed it live in the interest of time.

**Comment by carlacasilli** [comment]
Not sure why we're making people click on a link for the content that we're putting into a modal. Let's trim the content to this:

Welcome to the home for Open Badges badges. Join the evangelists, thinkers, and doers leading this global community. Come back to see new badge-earning opportunities as they become available to participate in the system as it grows!

Then there's no need for a modal (#31)

**Comment by emgollie** [comment]
Discussed with @carlacasilli. 

Welcome to the home for Open Badges badges. Join the evangelists, thinkers, and doers who are building this global community. Come back to see new badge-earning opportunities and participate in the system as it grows!

**Comment by carlacasilli** [comment]
:+1:
