### ISSUE TITLE
email claim bug

### ISSUE THREAD

**Issue by carlacasilli** [mozilla/openbadges-badges#32]
Moving to the appropriate repo: IGNORE

The email for claiming a MozFest badge is showing code where it should be showing the badge description:

![screen shot 2013-10-24 at 3 53 38 am](https://f.cloud.github.com/assets/1039302/1398414/ced23238-3ca0-11e3-9643-91b668987975.png)

**Comment by threeqube** [comment]
Clickable url should be this: http://badges.openbadges.org/badges#badgeaccept=mozfest-reveler&email=threeqube27%40gmail.com

**Comment by ghost** [comment]
This is fixed by #33 (both the _|BADGEDESC|_ issue and the email link).  Up for testing at obb-dev.herokuapp.com.
