### ISSUE TITLE
1-2-3 claim flow

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-badges#36]
Claim page should have breadcrumbs with
1. claim
2. store
3. show

Initially claim panel can be more or less as-is now (I think), store panel could just have backpack button and "what's backpack" help item, show could be placeholder panel.

**Comment by xmatthewx** [comment]
Design team had some feedback on the breadcrumb language. _Store_ is boring. _Use_ rather than _Show_ expands the possibilities (at least in theory).
- Claim, Store, Show
- Claim, Keep, Show 
- Claim It, Collect It, Use It

**Comment by xmatthewx** [comment]
Another question for consideration: since claim pages are sometimes heavily designed and branded for an event, do they include the breadcrumbs?

**Comment by threeqube** [comment]
> Claim It, Collect It, Use It

I kinda like this. But not in love with "use" frankly. cc/ @iamjessklein @megcolek

**Comment by stenington** [comment]
I also have a question about moving back and forth between the panels. Moving from **claim** to **collect** is pretty straightforward once the user has claimed their badge (which is pretty much a one-time deal) but then I could imagine a person might want to both download their badge and send it to their backpack, before then moving on to **use**.

Anyway, I think there's a slight asymmetry between going from **claim** to **collect** automatically but then wanting to bounce between **collect** and **use** through some sort of click navigation or whatever.

**Comment by xmatthewx** [comment]
After Claim, an earner has two options with Collect:

a) **Push to Backpack** -  Ideally, backpack will provide a [badge-centric view](http://moz.ideapublic.org/123/backpack.html) following a push with options to download/display and add to collections.

b) **Download** - Downloading then provides [display instructions](http://moz.ideapublic.org/123/show.html). I added a link to backpack for anyone overwhelmed by the details.

also) Everyone should receive an email confirmation that guides them toward backpack.

**Comment by emgollie** [comment]
I'm a little late to this conversation, forgive me. "Collect" to me suggests a mindset of "the more badges, the better!", which I think we want to avoid (personal meaning > quantity). What about "Claim It | Manage | Use It"?

**Comment by chloeatplay** [comment]
Just clicked through prototype, great work! Two things; 1,2,3 indicator dissappears at last screen (Show). Still a bit confused with button placement and page breakdown in 2 (Collect)- with the line division and 2 buttons. But that might be something you are planning to address later on :)

**Comment by iamjessklein** [comment]
This looks great @xmatthewx - the flow is definitely improved. 
I am wondering if you should de-prioritize one of the buttons, so that there is a clear call to action. 
The main competition that I see here is between the stepped navigation (which is telling the user to go through a flow) and the two buttons at the bottom of the screen (which interrupts that flow). 

I think that my mental model here expects the progress tracker to be the strongest part of the hierarchy.  Perhaps this could be reinforced with the UI.  In terms of the copy, what if you tried just explaining that they have 2 options (sort of teach the flow here a little bit - since both of the options (push to backpack and download) involve unfamiliar terminology as well as calls to action)?

**Comment by stenington** [comment]
#41 has gone in which provides a basic version of this. Sounds like it's still being discussed though, so I won't close this ticket yet, although it'll make my life easier if future changes to the 1-2-3 claim flow are requested in new tickets.

**Comment by iamjessklein** [comment]
agreed - don't close this ticket yet. Two things are still being discussed:
1. should we continue to include the "1 - 2 - 3" visual cues or is this an over- designed treatment?
2. in the event that someone is already in fact logged in to their back via persona - we are considering an entirely different kind of claim for that is more personalized for that user.

**Comment by threeqube** [comment]
> in the event that someone is already in fact logged in to their back via persona - we are considering an entirely different kind of claim for that is more personalized for that user.

I like this. :+1:

**Comment by carlacasilli** [comment]
Hey, @iamjessklein the 1-2-3 steps feel useful to me, although the visual representation of them feels a little awkward. Perhaps drop the outer lines that lead into 1-2-3?  

Also, I'm somewhat confused by terms, "claim, collect, show." For me, collect is a confusing term: I don't know what I'm collecting since I'm only working with one badge at a time and collect feels like a grouping verb. Reading @emgollie's suggestion of "manage" feels more comfortable to me.

**Comment by iamjessklein** [comment]
@carlacasilli right - we need to explore that with the actual ui design (we haven't explored the treatment yet). 
I also like the "manage" suggestion.

**Comment by threeqube** [comment]
Ok friends, where are we netting out here?

Claim <-- I think we all agree on this one
Collect / Manage ?
Share / Show ?

**Comment by carlacasilli** [comment]
Claim :+1: 
Manage :+1: 
Share :+1:

**Comment by emgollie** [comment]
What @carlacasilli said!

**Comment by xmatthewx** [comment]
I worry that Manage sounds tedious and/or boring. 

Consider the first-time badge earner and their new exciting experience. First task after claiming... Manage? Also, you can't do anything at this stage but save it. Manage sounds like so much more.

I think Collect makes sense. You get a card in cereal box. Collect all four! Got a new badge in your backpack? Add it to a collection. Alternatively: 

Claim, Keep, Share

Claim, Gather, Share

Claim, Save, Share

**Comment by emgollie** [comment]
I understand what you're saying @xmatthewx. I have concerns that "collect" and "gather" send a message that badges are made to be sought en masse and hoarded. We think of earners less as "collectors" than active learners who are putting badges (which they seek selectively) to work for them. 

"Keep" and "Share" seem to be at odds with each other and may come across as opposing components of privacy settings. "Claim, Save, Share" works better (plus, alliteration!), but I wonder if "save" helps with the excitement factor. What do people think of "curate" (if you were able to create Collections/Groups in the step no. 2 flow)? 

Taking a quick step back, do we want to factor discovery and pathways into these steps, knowing that those will be part of a release in the spring? Thanks all.

**Comment by threeqube** [comment]
I'm gonna let y'all talk this through. But let's make a decision soon. 

It seems like now
Claim :+1: 
Manage / Collect <-- this is still controversial
Share :+1:

**Comment by iamjessklein** [comment]
Manage sounds the most obvious in terms of mental models around what you expect to do when you get to that page.

**Comment by emgollie** [comment]
On today's research/badge system design call, our guest presenter raised the question of "how to we encourage a culture of learning in a world that emphasizes earning?" Good food for thought.

@xmatthewx: How do you recommend proceeding? We could also put "Manage" into the mockups and test alternate options with Backpack users.

**Comment by emgollie** [comment]
In thinking about this flow, I thought the new Creative Commons license steps were easy and potentially worth referencing: https://creativecommons.org/choose/

**Comment by xmatthewx** [comment]
Thanks for the link @emgollie.

"Claim, Manage, Share" seems like nearest to consensus. I recommend we close this ticket. This will be so easy to change later after trying it in the wild.

**Comment by emgollie** [comment]
Second the move to close. Thanks @xmatthewx.

**Comment by threeqube** [comment]
Copy ticket created for @stenington https://github.com/mozilla/openbadges-badges/issues/43
