### ISSUE TITLE
Email alert when someone applies for a badges

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges-badges#44]
When someone applies for a badge, send an email to assessors so they can review.

**Comment by threeqube** [comment]
This will be determined by account settings, no?

One can opt to have this feature turned on or off, right?

**Comment by carlacasilli** [comment]
Hey, I can't seem to login to http://badger.openbadges.org/admin. It's giving me an error page: is this just me or is this a bug?

**Comment by cmcavoy** [comment]
@threeqube this repo is for openbadges badges...the feature is just so we
know when someone has applied for a badge. This isn't a badgekit feature.

On Thu, Dec 5, 2013 at 6:59 PM, threeqube notifications@github.com wrote:

> This will be determined by account settings, no?
> 
> One can opt to have this feature turned on or off, right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadges-badges/issues/44#issuecomment-29954720
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by cmcavoy** [comment]
@carlacasilli looks like the database is down again on Heroku...will
investigate in the morning.

On Thu, Dec 5, 2013 at 10:49 PM, Carla Casilli notifications@github.comwrote:

> Hey, I can't seem to login to http://badger.openbadges.org/admin. It's
> giving me an error page: is this just me or is this a bug?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadges-badges/issues/44#issuecomment-29963489
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
@cmcavoy gotcha! Makes sense.

**Comment by carlacasilli** [comment]
@cmcavoy okay, thanks! I wanted to get on those badges that were outstanding, after your reminder. :watch: :smile:

**Comment by carlacasilli** [comment]
Just adding screenshot of the error: 
![screen shot 2013-12-06 at 1 10 14 pm](https://f.cloud.github.com/assets/1039302/1695942/e66938c4-5eba-11e3-80ea-4448bbd8643e.png)

**Comment by cmcavoy** [comment]
fixed!
