### ISSUE TITLE
badges.openbadges.org leads to an error page

### ISSUE THREAD

**Issue by carlacasilli** [mozilla/openbadges-badges#45]
This url: http://badges.openbadges.org/badges is throwing an error. Shouldn't this show all of the possible open badges badges?

**Comment by threeqube** [comment]
Yes it should. So weird. I _just_ checked this and it was working. cc/ @cmcavoy

**Comment by carlacasilli** [comment]
Still getting an error. 
![screen shot 2013-12-06 at 12 54 49 pm](https://f.cloud.github.com/assets/1039302/1695839/3aa9b69a-5eb9-11e3-8472-3dae228a747a.gif)

**Comment by cmcavoy** [comment]
Fixed! Openbadger was down.

**Comment by csprocket777** [comment]
What was causing this error? I'm experiencing the same situation on a self hosted instance of this.
